### ISSUE TITLE
Shortcode help Modal windows displacement.

### ISSUE THREAD

**Issue by linusrendahl** [MWDelaney/font-awesome-shortcodes#3]
![fontawesomeshortcode-error](https://cloud.githubusercontent.com/assets/7011353/3445420/4a0642f4-0137-11e4-9784-ebce55ec68e3.png)

When editing pages or posts, the modal "shortcode help" window is open by default.

It is placed way down below everything else at the bottom of the page.

The shortcode help button does nothing, doesnt close nor open the helper modal/window.

**Comment by linusrendahl** [comment]
Update: Actually, the help modal/window appears on EVERY page in admin, but without any css styling to it.

**Comment by MWDelaney** [comment]
Hi, @Mijhagi. I'm super sorry about this. I'm pushing a fix both here and on WordPress.org as I type this.

**Comment by linusrendahl** [comment]
I see that it's fixed now, thank you so much, great plugin!

**Comment by MWDelaney** [comment]
Thanks for your kind words and for your patience with this issue. Stupid mistake.
