### ISSUE TITLE
TablePress Support (feature)

### ISSUE THREAD

**Issue by emateu** [MWDelaney/font-awesome-shortcodes#6]
First of all, thanks for this plugin, is awesome!

TablePress seems to have an "Advanced Editor" feature where it opens in a lightbox a tiny WYSIWYG editor. There we have the "Font Awesome Shortcodes" icon (nice)!

The issue lives after choosing an icon: the click event seems to follow the <a> url and sends me out of the /wp-admin. Don't know if finally the shortcode was inserted or not!

![screenshot from 2015-01-09 17 23 43](https://cloud.githubusercontent.com/assets/629964/5686832/65d53c12-9825-11e4-8bb3-45249f66c080.png)

**Comment by MWDelaney** [comment]
Hi! Thanks for reporting this!

Okay so.. I kind of did the opposite of what you asked.

8cb20535229c358d201d71784cb5864b5dabc18b prevents the media buttons from showing in places where they won't work (like TablePress's Advanced Editor).

I'll investigate making this work for the future, but for now I wanted to make sure other users aren't confused by the unexpected behavior you reported!
